small improvements (#1)

diff --git a/git-squash b/git-squash
--- a/git-squash
+++ b/git-squash
@@ -1,9 +1,17 @@
-#!/bin/bash
+#!/bin/sh
 
-# Function to display error messages and exit
 fatal() {
-    echo "Error: $1" >&2
+    local RED="\033[0;31m"
+    local BOLD="\033[1m"
+    local RESET="\033[0m"
+    printf "${RED}${BOLD}Error: %s${RESET}\n" "$1" >&2
     exit 1
+}
+
+success() {
+    local GREEN="\033[0;32m"
+    local RESET="\033[0m"
+    printf "${GREEN}> %s${RESET}\n" "$1"
 }
 
 # Check for uncommitted changes
@@ -13,13 +21,13 @@ fi
 
 # Identify the main branch
 main_branch=$(git remote show origin | sed -n '/HEAD branch/s/.*: //p')
-if [ -z "$main_branch" ]; then
+if [ -z "$main_branch" ] || [ "$main_branch" == "(unknown)" ]; then
     fatal "Unable to identify the main branch."
 fi
 
 # Start the interactive rebase
 new_commit_message="$1"
-echo "Starting interactive rebase..."
+info "Starting interactive rebase..."
 if [ -n "$new_commit_message" ]; then
     GIT_SEQUENCE_EDITOR="sed -i '1s/pick/squash/'" git rebase -i --autosquash --autostash "$main_branch" && \
     git commit --amend -m "$new_commit_message"
@@ -32,4 +40,4 @@ if [ $? -ne 0 ]; then
 fi
 
 # Completing the squash process
-echo "All commits have been squashed into a single commit."
+success "All commits have been squashed into a single commit."
diff --git a/git-sync b/git-sync
--- a/git-sync
+++ b/git-sync
@@ -1,9 +1,23 @@
-#!/bin/bash
+#!/bin/sh
 
-# Function to display error messages and exit
 fatal() {
-    echo "Error: $1" >&2
+    local RED="\033[0;31m"
+    local BOLD="\033[1m"
+    local RESET="\033[0m"
+    echo -e "${RED}${BOLD}Error: $1${RESET}" >&2
     exit 1
+}
+
+info() {
+    local BLUE="\033[0;34m"
+    local RESET="\033[0m"
+    printf "${BLUE}> %s${RESET}\n" "$1"
+}
+
+success() {
+    local GREEN="\033[0;32m"
+    local RESET="\033[0m"
+    printf "${GREEN}> %s${RESET}\n" "$1"
 }
 
 # Check for correct usage
@@ -31,17 +45,25 @@ initial_branch=$(git branch --show-current)
 
 # Update the main branch
 main_branch=$(git remote show origin | sed -n '/HEAD branch/s/.*: //p')
-echo "Switching to $main_branch branch"
-git checkout "$main_branch"
-git pull origin "$main_branch"
-git checkout "$initial_branch"
-
-# Rebase onto the main branch
-echo "Rebasing $initial_branch on $main_branch"
-if $interactive; then
-    git rebase -i "$main_branch"
-else
-    git rebase "$main_branch"
+if [ -z "$main_branch" ] || [ "$main_branch" == "(unknown)" ]; then
+    fatal "Unable to identify the main branch."
 fi
 
-echo "$initial_branch synced with origin, $main_branch rebased"
+if [ "$local_branch" = "$main_branch" ]; then
+    git pull origin "$main_branch" --no-tags
+    success "'$main_branch' synced with origin"
+else
+    git checkout "$main_branch"
+    git pull origin "$main_branch" --no-tags
+    git checkout "$initial_branch"
+
+    # Rebase onto the main branch
+    info "Rebasing $initial_branch on $main_branch"
+    if $interactive; then
+        git rebase -i "$main_branch"
+    else
+        git rebase "$main_branch"
+    fi
+
+    success "'$initial_branch' synced with origin, '$main_branch' rebased"
+fi
